---
# yaml-language-server: $schema=https://json.schemastore.org/catalog-info.json
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: elasticsearch-py
spec:
  type: library
  owner: group:devtools-team
  lifecycle: production
  dependsOn:
    - "resource:elasticsearch-py"

---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/e57ee3bed7a6f73077a3f55a38e76e40ec87a7cf/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: elasticsearch-py
  description: elasticsearch-py integration tests
spec:
  type: buildkite-pipeline
  owner: group:devtools-team
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: elasticsearch-py integration tests
    spec:
      repository: elastic/elasticsearch-py
      pipeline_file: .buildkite/pipeline.yml
      env:
        ELASTIC_SLACK_NOTIFICATIONS_ENABLED: 'true'
        SLACK_NOTIFICATIONS_CHANNEL: '#devtools-notify-python'
      teams:
        devtools-team:
          access_level: MANAGE_BUILD_AND_READ
        everyone:
          access_level: READ_ONLY
      cancel_intermediate_builds: true
      cancel_intermediate_builds_branch_filter: '!main'
      schedules:
        main:
          branch: 'main'
          cronline: '0 10 * * *'
          message: 'Daily run for main branch'
        Daily 8.14:
          branch: '8.14'
          cronline: '0 10 * * *'
          message: 'Daily run for 8.14 branch'
        Daily 8.15:
          branch: '8.15'
          cronline: '0 10 * * *'
          message: 'Daily run for 8.15 branch'
