steps:
  - label: ":elasticsearch: :python: ES Python {{ matrix.python }} {{ matrix.nox_session }} ({{ matrix.connection }})"
    agents:
      provider: "gcp"
    env:
      PYTHON_VERSION: "{{ matrix.python }}"
      TEST_SUITE: "platinum"
      STACK_VERSION: "9.2.0-SNAPSHOT"
      PYTHON_CONNECTION_CLASS: "{{ matrix.connection }}"
      NOX_SESSION: "{{ matrix.nox_session }}"
    matrix:
      setup:
        python:
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
        connection:
          - "urllib3"
          - "requests"
        nox_session:
          - "test"
      adjustments:
        - with:
            python: "3.9"
            connection: "urllib3"
            nox_session: "test_otel"
        - with:
            python: "3.13"
            connection: "urllib3"
            nox_session: "test_otel"
    command: ./.buildkite/run-tests
