#!/usr/bin/env bash
#
# Version 1.1
# - Moved to .buildkite folder and separated out `run-repository.sh`
# - Add `$RUNSCRIPTS` env var for running Elasticsearch dependent products

# Default environment variables
export STACK_VERSION="${STACK_VERSION:=8.0.0-SNAPSHOT}"
export TEST_SUITE="${TEST_SUITE:=platinum}"
export PYTHON_VERSION="${PYTHON_VERSION:=3.9}"
export PYTHON_CONNECTION_CLASS="${PYTHON_CONNECTION_CLASS:=urllib3}"

script_path=$(dirname $(realpath -s $0))
source "$script_path/functions/imports.sh"
set -euo pipefail

echo "--- :elasticsearch: Starting Elasticsearch $STACK_VERSION"
DETACH=true bash .buildkite/run-elasticsearch.sh

if [[ -n "$RUNSCRIPTS" ]]; then
  for RUNSCRIPT in ${RUNSCRIPTS//,/ } ; do
    echo "--- Running run-$RUNSCRIPT.sh"
    CONTAINER_NAME="$RUNSCRIPT" \
      DETACH=true \
      bash ".buildkite/run-$RUNSCRIPT.sh"
  done
fi

echo "--- :python: Run tests"
bash .buildkite/run-repository.sh
