[[connecting]]
== Connecting

This page contains the information you need to connect the Client with {es}.


[discrete]
[[connect-url]]
==== Connecting with URLs

A single node can be specified via a `scheme`, `host`, `port`, and optional `path_prefix`. These values can either be specified manually via a URL in a string, dictionary, `NodeConfig`, or a list of these values. You must specify at least `scheme`, `host` and `port` for each node. All of the following are valid configurations:

[source,python]
----------------------------
from elasticsearch import Elasticsearch

# Single node via URL
es = Elasticsearch("http://localhost:9200")

# Multiple nodes via URL
es = Elasticsearch([
    "http://localhost:9200",
    "http://localhost:9201",
    "http://localhost:9202"
])

# Single node via dictionary
es = Elasticsearch({"scheme": "http", "host": "localhost", "port": 9200})

# Multiple nodes via dictionary
es = Elasticsearch([
    {"scheme": "http", "host": "localhost", "port": 9200},
    {"scheme": "http", "host": "localhost", "port": 9201},
])
----------------------------

[discrete]
[[connect-ec]]
==== Connecting to Elastic Cloud

Cloud ID is an easy way to configure your client to work with your Elastic Cloud 
deployment. Combine the `cloud_id` with either `basic_auth` or `api_key` to 
authenticate with your Elastic Cloud deployment.

Using `cloud_id` enables TLS verification and HTTP compression by default and 
sets the port to 443 unless otherwise overwritten via the port parameter or the 
port value encoded within `cloud_id`. Using Cloud ID also disables sniffing as
a proxy is in use.

[source,python]
----------------------------
from elasticsearch import Elasticsearch

es = Elasticsearch(
    cloud_id="cluster-1:dXMa5Fx..."
)
----------------------------


[discrete]
[[authentication]]
=== Authentication

This section contains code snippets to show you how to connect to various {es} 
providers. All authentication methods are supported on the client constructor
or via the per-request `.options()` method:

[source,python]
----------------------------
from elasticsearch import Elasticsearch

# Authenticate from the constructor
es = Elasticsearch(
    "http://localhost:9200",
    basic_auth=("username", "password")
)

# Authenticate via the .options() method:
es.options(
    basic_auth=("username", "password")
).indices.get(index="*")

# You can persist the authenticated client to use
# later or use for multiple API calls:
auth_client = es.options(
    api_key=("api-key-id", "api-key-secret")
)
for i in range(10):
    auth_client.index(
        index="example-index",
        document={"field": i}
    )
----------------------------


[discrete]
[[auth-basic]]
==== HTTP Basic authentication (Username and Password)

HTTP Basic authentication uses the `basic_auth` parameter by passing in a username and 
password within a tuple:

[source,python]
----------------------------
from elasticsearch import Elasticsearch

# Adds the HTTP header 'Authorization: Basic <base64 username:password>'
es = Elasticsearch(
    basic_auth=("username", "password")
)
----------------------------


[discrete]
[[auth-bearer]]
==== HTTP Bearer authentication

HTTP Bearer authentication uses the `bearer_auth` parameter by passing the token
as a string. This authentication method is used by 
https://www.elastic.co/guide/en/elasticsearch/reference/master/security-api-create-service-token.html[Service Account Tokens]
and https://www.elastic.co/guide/en/elasticsearch/reference/master/security-api-get-token.html[Bearer Tokens].

[source,python]
----------------------------
from elasticsearch import Elasticsearch

# Adds the HTTP header 'Authorization: Bearer token-value'
es = Elasticsearch(
    bearer_auth="token-value"
)
----------------------------


[discrete]
[[auth-apikey]]
==== API Key authentication

You can configure the client to use {es}'s API Key for connecting to your 
cluster. Note that you need the values of `id` and `api_key` to
[authenticate via an API Key](https://www.elastic.co/guide/en/elasticsearch/reference/current/security-api-create-api-key.html).

[source,python]
----------------------------
from elasticsearch import Elasticsearch

# Adds the HTTP header 'Authorization: ApiKey <base64 api_key.id:api_key.api_key>'
es = Elasticsearch(
    api_key=("api_key.id", "api_key.api_key")
)
----------------------------

[discrete]
[[compatibility-mode]]
=== Enabling the Compatibility Mode

The Elasticsearch server version 8.0 is introducing a new compatibility mode that allows you a smoother upgrade
experience from 7 to 8. In a nutshell, you can use the latest 7.x Python Elasticsearch Elasticsearch client with
an 8.x Elasticsearch server, giving more room to coordinate the upgrade of your codebase to the next major version. 

If you want to leverage this functionality, please make sure that you are using the latest 7.x Python Elasticsearch
client and set the environment variable `ELASTIC_CLIENT_APIVERSIONING` to `true`. The client is handling the rest
internally. For every 8.0 and beyond Python Elasticsearch client, you're all set! The compatibility mode
is enabled by default.

[discrete]
[[connecting-faas]]
=== Using the Client in a Function-as-a-Service Environment

This section illustrates the best practices for leveraging the {es} client in a Function-as-a-Service (FaaS) environment.
The most influential optimization is to initialize the client outside of the function, the global scope.
This practice does not only improve performance but also enables background functionality as – for example –
https://www.elastic.co/blog/elasticsearch-sniffing-best-practices-what-when-why-how[sniffing].
The following examples provide a skeleton for the best practices.

IMPORTANT: The async client shouldn't be used within Function-as-a-Service as a new event
           loop must be started for each invocation. Instead the synchronous `Elasticsearch`
           client is recommended.

[discrete]
[[connecting-faas-gcp]]
==== GCP Cloud Functions

[source,python]
----------------------------
from elasticsearch import Elasticsearch

client = Elasticsearch(
    ... # Client initialization
)

def main(request):
    ... # Use the client

----------------------------

[discrete]
[[connecting-faas-aws]]
==== AWS Lambda

[source,python]
----------------------------
from elasticsearch import Elasticsearch

client = Elasticsearch(
    ... # Client initialization
)

def main(event, context):
    ... # Use the client

----------------------------

[discrete]
[[connecting-faas-azure]]
==== Azure Functions

[source,python]
----------------------------
import azure.functions as func
from elasticsearch import Elasticsearch

client = Elasticsearch(
    ... # Client initialization
)

def main(request: func.HttpRequest) -> func.HttpResponse:
    ... # Use the client

----------------------------

Resources used to assess these recommendations:

* https://cloud.google.com/functions/docs/bestpractices/tips#use_global_variables_to_reuse_objects_in_future_invocations[GCP Cloud Functions: Tips & Tricks]
* https://docs.aws.amazon.com/lambda/latest/dg/best-practices.html[Best practices for working with AWS Lambda functions]
* https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-python?tabs=azurecli-linux%2Capplication-level#global-variables[Azure Functions Python developer guide]
* https://docs.aws.amazon.com/lambda/latest/operatorguide/global-scope.html[AWS Lambda: Comparing the effect of global scope]
