[[release-notes]]
== Release notes

* <<rn-8-9-0>>
* <<rn-8-8-0>>
* <<rn-8-7-0>>
* <<rn-8-6-2>>
* <<rn-8-6-1>>
* <<rn-8-6-0>>
* <<rn-8-5-3>>
* <<rn-8-5-2>>
* <<rn-8-5-1>>
* <<rn-8-5-0>>
* <<rn-8-4-3>>
* <<rn-8-4-2>>
* <<rn-8-4-1>>
* <<rn-8-4-0>>
* <<rn-8-3-3>>
* <<rn-8-3-2>>
* <<rn-8-3-1>>
* <<rn-8-3-0>>
* <<rn-8-2-3>>
* <<rn-8-2-2>>
* <<rn-8-2-1>>
* <<rn-8-2-0>>
* <<rn-8-1-2>>
* <<rn-8-1-1>>
* <<rn-8-1-0>>
* <<rn-8-0-0>>

[discrete]
[[rn-8-9-0]]
=== 8.9.0 (2023-07-27)

* Added the [`cluster.info`](https://www.elastic.co/guide/en/elasticsearch/reference/8.9/cluster-info.html) API
* Updated the `inference_config` argument in `ml.put_trained_model` API to reflect an improvement in the specification

[discrete]
[[rn-8-8-0]]
=== 8.8.0 (2023-05-25)

* Added `include_defaults` parameter to the `cluster.get_component_template`, `indices.get_data_stream`, and `indices.get_index_template` API
* Added the `indices.delete_data_lifecycle`, `indices.explain_data_lifecycle`, `indices.get_data_lifecycle`, and `indices.put_data_lifecycle` APIs
* Added the **experimental** `search_application.delete`, `search_application.delete_behavioral_analytics`, `search_application.get`, `search_application.get_behavioral_analytics`, `search_application.list`, `search_application.put`, `search_application.put_behavioral_analytics`, and `search_application.search` APIs.

[discrete]
[[rn-8-7-0]]
=== 8.7.0 (2023-04-06)

* Added the ``health_report`` API
* Added the ``transform.schedule_now_transform`` API
* Added the ``from_`` request parameter to the ``transform.start_transform`` API
* Added the ``buffer``, ``grid_agg``, and ``with_labels`` parameters to the ``search_mvt`` API
* Added the ``allow_auto_create`` parameter to the ``cluster.create_component_template`` API
* Added the ``delete_user_annotations`` parameter to the ``ml.delete_job``, ``ml.reset_job`` API
* Added the ``start`` and ``end`` parameters to the ``ml.preview_datafeed`` API
* Added the ``priority`` parameter to the ``ml.start_datafeed`` API
* Added the ``job_id`` parameter to the ``ml.update_datafeed`` API
* Added the ``model_prune_window`` parameter to the ``ml.update_job`` API
* Added the ``feature_states`` parameter to the ``snapshot.restore_snapshot`` API
* Added the ``timeout`` parameter to the ``transform.get_transform_stats`` API
* Added the ``from_`` parameter to the ``transform.start_transform`` API
* Changed the ``input`` parameter of the ``ml.put_trained_models`` API from required to optional
* Fixed the ``cluster.create_component_template`` API by removing the erroneously provided ``aliases``, ``mappings``, and ``settings`` parameters. Only the ``template`` parameter should be used for specifying component templates.

[discrete]
[[rn-8-6-2]]
=== 8.6.2 (2023-02-16)

* Client is compatible with Elasticsearch 8.6.2

[discrete]
[[rn-8-6-1]]
=== 8.6.1 (2023-01-27)

* Client is compatible with Elasticsearch 8.6.1

[discrete]
==== Core

* Added the `expand_wildcards`, `preference`, and `routing` parameters to the `open_point_in_time` API.

[discrete]
[[rn-8-6-0]]
=== 8.6.0 (2023-01-10)

* Client is compatible with Elasticsearch 8.6.0

[discrete]
==== Core

* Changed the `fields` parameter of the `field_caps` API to be encoded in the HTTP request body.
* Changed the `index` parameter of the `rank_eval` API to be optional.
* Changed the `requests` parameter of the `rank_eval` API to be optional.

[discrete]
==== CAT

* Added the `time` parameter to the `cat.indices` API

[discrete]
==== Machine Learning

* Fixed the `model_id` parameter of the `ml.clear_trained_model_deployment_cache` API to be required.

[discrete]
[[rn-8-5-3]]
=== 8.5.3 (2022-12-08)

* Client is compatible with Elasticsearch 8.5.3

[discrete]
[[rn-8-5-2]]
=== 8.5.2 (2022-11-23)

* Client is compatible with Elasticsearch 8.5.2

[discrete]
[[rn-8-5-1]]
=== 8.5.1 (2022-11-21)

* Client is compatible with Elasticsearch 8.5.1

[discrete]
[[rn-8-5-0]]
=== 8.5.0 (2022-11-2)

[discrete]
==== Indices

* Added the **experimental** `indices.downsample` API

[discrete]
==== Rollup

* Removed the deprecated `rollup.rollup` API.

[discrete]
==== Snapshot

* Added the `index_names` parameter to the `snapshot.get` API.

[discrete]
==== Machine Learning

* Added the **beta** `ml.clear_trained_model_deployment_cache` API.
* Changed the `ml.put_trained_model_definition_part` API from **experimental** to **stable**.
* Changed the `ml.put_trained_model_vocabulary` API from **experimental** to **stable**.
* Changed the `ml.start_trained_model_deployment` API from **experimental** to **stable**.
* Changed the `ml.stop_trained_model_deployment` API from **experimental** to **stable**.

[discrete]
==== Security

* Added the `with_limited_by` parameter to the `get_api_key` API.
* Added the `with_limited_by` parameter to the `query_api_keys` API.
* Added the `with_profile_uid` parameter to the `get_user` API.
* Changed the `security.activate_user_profile` API from **beta** to **stable**.
* Changed the `security.disable_user_profile` API from **beta** to **stable**.
* Changed the `security.enable_user_profile` API from **beta** to **stable**.
* Changed the `security.get_user_profile` API from **beta** to **stable**.
* Changed the `security.suggest_user_profiles` API from **beta** to **stable**.
* Changed the `security.update_user_profile_data` API from **beta** to **stable**.
* Changed the `security.has_privileges_user_profile` API from **experimental** to **stable**.

[discrete]
[[rn-8-4-3]]
=== 8.4.3 (2022-10-06)

* Client is compatible with Elasticsearch 8.4.3

[discrete]
[[rn-8-4-2]]
=== 8.4.2 (2022-09-20)

[discrete]
==== Documents

* Added the `error_trace`, `filter_path`, `human` and `pretty` parameters to the `get_source` API.
* Added the `ext` parameter to the `search` API.

[discrete]
==== Async Search

* Added the `ext` parameter to the `async_search.submit` API.

[discrete]
==== Fleet

* Added the `ext` parameter to the `fleet.search` API.

[discrete]
[[rn-8-4-1]]
=== 8.4.1 (2022-09-06)

* Client is compatible with Elasticsearch 8.4.1

[discrete]
[[rn-8-4-0]]
=== 8.4.0 (2022-08-25)

[discrete]
==== Search

* Added the `knn` parameter to the `search` API.
* Added the `knn` parameter to the `async_search.submit` API.

[discrete]
==== Machine Learning

* Added the `cache_size` parameter to the `ml.start_trained_model_deployment` API.

[discrete]
==== Security

* Added the `security.update_api_key` API.

[discrete]
[[rn-8-3-3]]
=== 8.3.3 (2022-08-01)

* Client is compatible with Elasticsearch 8.3.3

[discrete]
[[rn-8-3-2]]
=== 8.3.2 (2022-08-01)

[discrete]
==== Security

* Added the `refresh` parameter to the `security.create_service_token` API.

[discrete]
[[rn-8-3-1]]
=== 8.3.1 (2022-06-30)

[discrete]
==== Security

* Added the **experimental** `security.has_privileges_user_profile` API.
* Added the `hint` parameter to the **experimental** `security.suggest_user_profiles` API.

[discrete]
[[rn-8-3-0]]
=== 8.3.0 (2022-06-29)

* Client is compatible with Elasticsearch 8.3.0

[discrete]
[[rn-8-2-3]]
=== 8.2.3 (2022-06-15)

[discrete]
==== Documents

* Added the `routing` parameter to the `msearch` API.

[discrete]
==== CAT

* Added the `cat.component_templates` API.

[discrete]
==== Ingest

* Added the `if_version` parameter to the `ingest.put_pipeline` API.

[discrete]
==== Security

* Changed the `name` parameter for the `security.create_service_token` API from required to optional.
* Added the `refresh` parameter to the `security.create_service_token` API.
* Changed the name of `access` parameter to the `labels` parameter in the `security.update_user_profile_data` API.

[discrete]
==== Shutdown

* Added the `timeout` and `master_timeout` parameters to the `shutdown.get_node`, `shutdown.delete_node`, and `shutdown.put_node` APIs.
* Added the `reason`, `type`, `allocation_delay`, and `target_node_name` parameters to the `shutdown.put_node` API.

[discrete]
[[rn-8-2-2]]
=== 8.2.2 (2022-06-01)

* Client is compatible with Elasticsearch 8.2.2

[discrete]
[[rn-8-2-1]]
=== 8.2.1 (2022-06-01)

[discrete]
==== Machine Learning

* Added the `inference_config` parameter to the `ml.infer_trained_model_deployment` API

[discrete]
[[rn-8-2-0]]
=== 8.2.0 (2022-05-03)

[discrete]
==== Client

* Re-introduced support for passing `requests.auth.BaseAuth` objects to the `http_auth` parameter which was available in 7.x.

[discrete]
==== Search

* Added the `filter` parameter to the **experimental** `knn_search` API

[discrete]
==== Documents

* Changed the `source` and `dest` parameters for the `reindex` API from optional to required

[discrete]
==== Indices

* Added the `indices.field_usage_stats` API
* Added the `indices.modify_data_stream` API
* Added the `fields` and `types` parameters to the `field_caps` API
* Added the `ignore_unvailable` parameter to the `open_point_in_time` API
* Added the `master_timeout` and `timeout` parameters to the `indices.delete` API
* Added the `features` parameter to the `indices.get` API

[discrete]
==== Machine Learning

* Added the `ml.get_memory_stats` API

[discrete]
==== Migrations

* Added the `migrations.get_feature_upgrade_status` API
* Added the `migrations.post_feature_upgrade` API

[discrete]
==== Nodes

* Added the `nodes.clear_repositories_metering_archive` API
* Added the `nodes.get_repositories_metering_info` API

[discrete]
==== Security

* Added the **beta** `security.activate_user_profile` API
* Added the **beta** `security.disable_user_profile` API
* Added the **beta** `security.enable_user_profile` API
* Added the **beta** `security.get_user_profile` API
* Added the **beta** `security.suggest_user_profiles` API
* Added the **beta** `security.update_user_profile_data` API

[discrete]
==== SQL

* Added the `catalog`, `index_using_frozen`, `keep_alive`, `keep_on_completion`, `runtime_mappings`, and `wait_for_completion_timeout` parameters to the `sql.query` API

[discrete]
[[rn-8-1-2]]
=== 8.1.2 (2022-03-30)

* Client is compatible with Elasticsearch 8.1.2


[discrete]
[[rn-8-1-1]]
=== 8.1.1 (2022-03-22)

[discrete]
==== Documents

* Changed the `source` and `dest` parameters of the `reindex` API to be required.

[discrete]
==== Mappings

* Changed the `fields` parameter of the `field_caps` API to be required.


[discrete]
[[rn-8-1-0]]
=== 8.1.0 (2022-03-08)

[discrete]
==== Transforms

* Added the `transform.reset_transform` API


[discrete]
[[rn-8-0-0]]
=== 8.0.0 (2022-02-10)

[discrete]
==== Added

* Added the top-level `.options()` method to `Elasticsearch` and `AsyncElasticsearch` for modifying transport options.
* Added parameters corresponding to JSON request body fields for all APIs
* Added `basic_auth` parameter for specifying username and password authentication
* Added `bearer_auth` parameter for specifying an HTTP bearer token or service token
* Added the `meta` property to `ApiError` to access the HTTP response metadata of an error.
* Added a check that a compatible version of the `elastic-transport` package is installed.

[discrete]
==== Changed

* Changed the transport layer to use the `elastic-transport` package
* Changed user-defined `body` parameters to have semantic names (e.g `index(document={...})` instead of `index(body={...})`).
* Changed responses to be objects with two properties, `meta` for response metadata (HTTP status, headers, node, etc) and `body` for a typed body.
* Changed `AsyncElasticsearch` to always be available, regardless of whether `aiohttp` is installed
* Changed exception hierarchy, the major change is a new exception `ApiError` which differentiates between an error that's raised from the transport layer (previously `elasticsearch.exceptions.TransportError`, now `elastic_transport.TransportError`) and one raised from the API layer
* Changed the name of `JSONSerializer` to `JsonSerializer` for consistency with other serializer names. Added an alias to the old name for backwards compatibility
* Changed the default mimetypes (`application/json`) to instead use compatibility mimetypes (`application/vnd.elasticsearch+json`) which always request for responses compatibility with version 8.x.

[discrete]
==== Removed

* Removed support for Python 2.7 and Python 3.5, the library now supports only Python 3.6+
* Removed the `elasticsearch.connection` module as all functionality has been moved to the `elastic-transport` package
* Removed the default URL of `http://localhost:9200` due to Elasticsearch 8.0 default configuration being `https://localhost:9200`.
  The client's connection to Elasticsearch now must be specified with scheme, host, and port or with the `cloud_id` parameter
* Removed the ability to use positional arguments with API methods. Going forward all API parameters must be keyword-only parameters
* Removed the `doc_type`, `include_type_name`, and `copy_settings` parameters from many document and index APIs

[discrete]
==== Deprecated

* Deprecated the `body` and `params` parameters on all APIs
* Deprecated setting transport options `http_auth`, `api_key`, `ignore`, `request_timeout`, `headers`, and `opaque_id`
  All of these settings should instead be set via the `.options()` method
* Deprecated the `elasticsearch.transport` and `elasticsearch.client` modules. These modules will be removed in a future version

[discrete]
==== CAT

* Removed the deprecated `local` parameter from the `cat.indices`, `cat.nodes`, `cat.shards` API
* Removed the deprecated `allow_no_datafeeds` parameter from the `cat.ml_datafeeds` API
* Removed the deprecated `allow_no_jobs` parameter from the `cat.ml_jobs` API
* Removed the deprecated `size` parameter from the `cat.thread_pool` API
* Added the `time` parameter to the `cat.thread_pool` API

[discrete]
==== Documents

* Removed the deprecated `size` parameter from the `delete_by_query` API
* Removed the deprecated `size` parameter from the `update_by_query` API

[discrete]
==== Indices

* Removed the deprecated `indices.flush_synced` API
* Removed the deprecated `indices.freeze` API
* Removed the deprecated `indices.get_upgrade` API
* Removed the deprecated `indices.upgrade` API
* Removed the deprecated `indices.exist_type` API
* Removed the deprecated parameter `copy_settings` from the `indices.shrink` API
* Deprecated the `verbose` parameter of the `indices.segments` API

[discrete]
==== License / X-Pack

* Deprecated the `accept_enterprise` parameter of the `license.get` API
* Deprecated the `accept_enterprise` parameter of the `xpack.info` API

[discrete]
==== Machine Learning

* Added the **experimental** `ml.infer_trained_model_deployment` API
* Added the **experimental** `ml.put_trained_model_definition_part` API
* Added the **experimental** `ml.put_trained_model_vocabulary` API
* Added the **experimental** `ml.start_trained_model_deployment` API
* Added the **experimental** `ml.stop_trained_model_deployment` API
* Added the `timeout` parameter to the `ml.delete_trained_model` API
* Removed the deprecated `allow_no_jobs` parameter from the `ml.close_job` API
* Removed the deprecated `ml.find_text_structure` API
* Removed the deprecated `allow_no_datafeeds` parameter from the `ml.get_datafeed_stats` API
* Removed the deprecated `allow_no_datafeeds` parameter from the `ml.get_datafeeds` API
* Removed the deprecated `allow_no_jobs` parameter from the `ml.get_job_stats` API
* Removed the deprecated `allow_no_jobs` parameter from the `ml.get_jobs` API
* Removed the deprecated `allow_no_jobs` parameter from the `ml.get_overall_buckets` API

[discrete]
==== Search

* Added the **experimental** `knn_search` API

[discrete]
==== Searchable Snapshots

* Removed the deprecated `searchable_snapshots.repository_stats` API

[discrete]
==== Snapshots

* Changed the `snapshot.delete` API to accept multiple snapshots

[discrete]
==== Security

* Added the `security.enroll_kibana` API
* Added the `security.enroll_node` API
