version: "3"

services:
  elasticsearch:
    image: elasticsearch:8.13.0
    environment:
      - discovery.type=single-node
      - xpack.license.self_generated.type=trial
      - xpack.security.enabled=false  # disable password and TLS; never do this in production!
    ports:
      - "9200:9200"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --silent --fail http://localhost:9200/_cluster/health || exit 1"
        ]
      interval: 10s
      retries: 60

  kibana:
    image: kibana:8.13.0
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - "5601:5601"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --silent --fail http://localhost:5601/login || exit 1"
        ]
      interval: 10s
      retries: 60
