[project]
name = "quotes"
version = "0.1"
dependencies = [
    "elasticsearch[async]>=8,<9",
    "fastapi",
    "orjson",
    "sentence-transformers",
    "uvicorn",
]

[project.optional-dependencies]
dev = [
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
