#
# Autogenerated by Thrift Compiler (0.9.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py:new_style=true,utf8strings=true
#

from thrift.Thrift import TType, TMessageType, TException, TApplicationException
from ttypes import *

